#!/bin/bash
hostname="$1"
TUNNEL=""

function write_combined () {
        OLD_FILE=/tmp/snmp_decode_$STB
        NEW_FILE=/tmp/snmp_decodecompare_$STB
                if [ -s $NEW_FILE ]; then
                        mv -f $NEW_FILE $OLD_FILE > /dev/null 2>&1
			if [ $? -gt 0 ]; then
				echo 0
				exit 0
			fi
                        ssh root@$TUNNEL "/root/tbaker/check_server $STB" > /dev/null 2>&1
                        scp -q root@$TUNNEL:/tmp/decode_$STB $NEW_FILE > /dev/null 2>&1
			if [ $? -gt 0 ]; then
                                echo 0
                                exit 0
                        fi
                        check_output
                else
                        ssh root@$TUNNEL "/root/tbaker/check_server $STB" > /dev/null 2>&1
                        scp -q root@$TUNNEL:/tmp/decode_$STB $NEW_FILE
                        no_file
                fi
}

function no_file () {
	echo 0
	exit 0
}

function check_output () {
	if [ ! -s $OLD_FILE ]; then
		echo 0
		exit 0
	elif [ ! -s $NEW_FILE ]; then
		echo 0
		exit 0
	fi
	PREV_VID_DECODES=$(sed -n '1p' $OLD_FILE)
	PREV_VID_ERRORS=$(sed -n '2p' $OLD_FILE)
	PREV_AUDIO_DECODES=$(sed -n '3p' $OLD_FILE)
	PREV_AUDIO_ERRORS=$(sed -n '4p' $OLD_FILE)
	
	VID_DECODES=$(sed -n '1p' $NEW_FILE)
	VID_ERRORS=$(sed -n '2p' $NEW_FILE)
	AUDIO_DECODES=$(sed -n '3p' $NEW_FILE)
	AUDIO_ERRORS=$(sed -n '4p' $NEW_FILE)

	if [ "$method" = "total_video" ]; then
		echo "$VID_DECODES"
		exit $VID_DECODES
	elif [ "$method" = "total_audio" ]; then
		echo "$AUDIO_DECODES"
		exit $AUDIO_DECODES
	elif [ "$method" = "total_video_error" ]; then
		echo "$VID_ERRORS"
		exit $VID_ERRORS
	elif [ "$method" = "total_audio_error" ]; then
		echo "$AUDIO_ERRORS"
		exit $AUDIO_ERRORS
	else
		check_diff
	fi
}

function check_diff () {
#		let TOTAL_VIDEO_DECODE="$VID_DECODES - $PREV_VID_DECODES"
#		let TOTAL_AUDIO_DECODE="$AUDIO_DECODES - $PREV_AUDIO_DECODES"
#		let TOTAL_VIDEO_ERRORS="$VID_ERRORS - $PREV_VID_ERRORS"
#		let TOTAL_AUDIO_ERRORS="$AUDIO_ERRORS - $PREV_AUDIO_ERRORS"
		((TOTAL_VIDEO_DECODE="$VID_DECODES - $PREV_VID_DECODES")) > /dev/null 2>&1
		((TOTAL_AUDIO_DECODE="$AUDIO_DECODES - $PREV_AUDIO_DECODES")) > /dev/null 2>&1
		((TOTAL_VIDEO_ERRORS="$VID_ERRORS - $PREV_VID_ERRORS")) > /dev/null 2>&1
		((TOTAL_AUDIO_ERRORS="$AUDIO_ERRORS - $PREV_AUDIO_ERRORS")) > /dev/null 2>&1
				if [ "$method" = "last_video" ]; then
					echo $TOTAL_VIDEO_DECODE
					exit $TOTAL_VIDEO_DECODE
				elif [ "$method" = "last_audio" ]; then
					echo $TOTAL_AUDIO_DECODE
					exit $TOTAL_AUDIO_DECODE
				elif [ "$method" = "last_video_error" ]; then
					echo $TOTAL_VIDEO_ERRORS
					exit $TOTAL_VIDEO_ERRORS
				elif [ "$method" = "last_audio_error" ]; then
					echo $TOTAL_AUDIO_ERRORS
					exit $TOTAL_AUDIO_ERRORS
				else
					echo 0
					exit 0
				fi
}

function check_telnet () {
	ssh root@$TUNNEL "nc -z -w2 $STB 23"
	if [ $? -gt 0 ]; then
		echo 0
		exit 0
	else
		write_combined
	fi
}
method=$1
STB=$2
check_telnet
